config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/', to: 'sessions#welcome'
  resources :properties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized
    helper_method :current_user
    helper_method :logged_in?
    helper_method :is_manager?
    
    def current_user
        User.find(session[:user_id])
    end

    def logged_in?
        !session[:user_id].nil?
    end

    def is_manager?
        logged_in? && current_user.role == 'manager'
    end

    def authorized
        redirect_to '/' unless logged_in?
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
    def index
        @properties = Property.all
    end

    def new
    end

    def create
        @property = Property.new(property_params)

        @property.save
        redirect_to @property
    end
    
    def show
        @property = Property.find(params[:id])
    end

    private
        def property_params
            params.require(:property).permit(:type, :owner, :address, :rooms, :units, :shops, :sqmt, :floors, :parking, :air_cond, :price)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def login
  end

  def welcome
    if logged_in?
      redirect_to '/properties'
    else
      redirect_to '/login'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @existing = User.find_by(username: params[:user][:username])

    if @existing
      redirect_to '/users/new'
    else
      @user = User.create(params.require(:user).permit(:username, :role, :password))
      session[:user_id] = @user.id
      redirect_to '/'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/realestates_helper.rb
module RealestatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Real Estate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/index.html.erb
<h1>Properties</h1>

<% if is_manager? %>
    <%= link_to "Add property", '/properties/new', class: 'button alt' %>
<% end %>

<table>
    <tr>
        <th>Owner</th>
        <th>Address</th>
    </tr>

    <% @properties.each do |property| %>
        <tr>
            <td><%= property.owner %></td>
            <td><%= property.address %></td>
        </tr>
    <% end %>
</table>

app/views/properties/new.html.erb
<%= form_with scope: :property, url: properties_path, local: true do |form| %>
    <p>
        <%= form.label :type %>
        <%= form.select(:type, ['House', 'Complex Building', 'Commercial Unit']) %>
    </p>

    <p>
        <%= form.label :address %>
        <%= form.text_field :address %>
    </p>

    <p>
        <%= form.label :rooms %>
        <%= form.number_field :rooms %>
    </p>

    <p>
        <%= form.label :units %>
        <%= form.number_field :units %>
    </p>

    <p>
        <%= form.label :shops %>
        <%= form.number_field :shops %>
    </p>

    <p>
        <%= form.label :sqmt %>
        <%= form.number_field :sqmt %>
    </p>

    <p>
        <%= form.label :parking %>
        <%= form.number_field :parking %>
    </p>

    <p>
        <%= form.label :floors %>
        <%= form.number_field :floors %>
    </p>

    <p>
        <%= form.label :air_cond %>
        <%= form.check_box :air_cond %>
    </p>    

    <p>
        <%= form.label :price %>
        <%= form.number_field :price %>
    </p>

    <%= hidden_field_tag "owner", current_user.id %>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/properties/show.html.erb
<p>
    <string>Owner:</strong>
    <%= @property.owner %>
</p>

<p>
    <string>Address:</strong>
    <%= @property.address %>
</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br><br>
    <%= f.label :role %>
    <%= f.text_field :role %>
    <br><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br>
    <br><br>
    <%= f.submit "Sign Up" %>
    <br><br>
    <%= link_to "Already have an account?", '/login', class: 'button alt' %>
<% end %>